services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    volumes:
      - ./:/home/node/.n8n/custom/n8n-nodes-carddav-rest:ro
      - n8n-data:/home/node/.n8n
    environment:
      N8N_CUSTOM_EXTENSIONS: /home/node/.n8n/custom
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  n8n-data:
